### ISSUE TITLE
Can't add or disable plugin

### ISSUE THREAD

**Issue by horosgrisa** [CHENXCHEN/hexo-renderer-markdown-it-plus#1]
I can't add or remove plugin when I use `_config.yml`

This doesn't work:
```yaml
        - plugin:
            name: markdown-it-container
            enable: true
        - plugin:
            name: markdown-it-sub
            enable: false
        - plugin:
            name: markdown-it-sup
            enable: false
```

**Comment by CHENXCHEN** [comment]
It is work for me when i use `config.yml`, see the code below.
```yml
markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    pre_class: highlight
    plugins:
        - plugin:
            name: markdown-it-sub
            enable: false
        - plugin:
            name: markdown-it-sup
            enable: false
```
When i config it, it shown as below:
![image](https://user-images.githubusercontent.com/7724525/29464740-6125cc08-8469-11e7-8670-b402b187c02e.png)
The default is shown as below:
![image](https://user-images.githubusercontent.com/7724525/29464774-83f5dab6-8469-11e7-9bee-e061c5457fc1.png)

tips: maybe you need `hexo clean` for test.
