### ISSUE TITLE
更新Katex版本

### ISSUE THREAD

**Issue by hzqjyyx** [CHENXCHEN/hexo-renderer-markdown-it-plus#10]
markdown-it-katex好像很久没有更新过了，有个fork过的[iktakahiro/markdown-it-katex](https://github.com/iktakahiro/markdown-it-katex/)看起来做了一写修改，我想在_config.yml文件中禁用默认的markdown-it-katex，使用这个新的，但是看起来并没有效果。
```
markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  plugins:
  - plugin:
    name: '@iktakahiro/markdown-it-katex'
    enable: true
  - plugin:
    name: markdown-it-katex
    enable: false
```
使用了hexo-theme-next主题，在next/_config.yml中修改katex的版本为0.9.0.
请问如何做能使用这个库呢？

**Comment by CHENXCHEN** [comment]
我在本地测试了使用该插件是可用的。
你只需要引入 `katex.min.css` 就可以使用了
如： `//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css`
```yml
markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    pre_class: highlight
    plugins:
        - plugin:
            name: markdown-it-mark
            enable: false
        - plugin:
            name: markdown-it-katex
            enable: false
        - plugin:
            name: '@iktakahiro/markdown-it-katex'
            enable: true
```
