### ISSUE TITLE
toc and anchor plugin

### ISSUE THREAD

**Issue by noraj** [CHENXCHEN/hexo-renderer-markdown-it-plus#13]
You say you are using [markdown-it-toc-and-anchor](https://www.npmjs.com/package/markdown-it-toc-and-anchor) but in [dependencies](hexo-renderer-markdown-it-plus) I see only [markdown-it-toc](https://www.npmjs.com/package/markdown-it-toc) that is not the same plugin.

Which one is used ?

And you said in the README that `markdown-it-toc-and-anchor` is enabled by default but no TOC are generated by default so does this mean we need to do `npm i markdown-it-toc-and-anchor --save` before ?

And how to configure it ? Like that ?

```yaml
markdown_it_plus:
    # ...
    plugins:
        - plugin:
            name: markdown-it-toc-and-anchor
            enable: true # not needed if enabled by default ????
            options:
                toc: true
                tocClassName: 'markdownIt-TOC'
                tocFirstLevel: 1
                tocLastLevel: 6
                tocCallback:
                anchorLink: true
                anchorLinkSymbol: '#'
                anchorLinkSpace: true
                anchorLinkSymbolClassName:
                anchorLinkBefore: true
                anchorClassName: 'markdownIt-Anchor'
                resetIds: true
```
