### ISSUE TITLE
Can't use markdown-it-center-text

### ISSUE THREAD

**Issue by MayakoLyyn** [CHENXCHEN/hexo-renderer-markdown-it-plus#14]
Hello,

I just tried your plugin and it works fine so far (although I'll have one question later). I wanted to add this markdown-it plugin: [markdown-it-center-text](https://www.npmjs.com/package/markdown-it-center-text) but it doesn't work at all. I get no error when I generate my site (even after an *hexo clean*).

What I did:

* `npm install markdown-it-center-text --save`
* added the following lines in my main **_config_yml**: 
```
markdown_it_plus:
    plugins:
      - plugin:
        name: markdown-it-center-text
        enable: true
```
* added a test line in an article: `->blabla<-`
* `hexo clean; hexo generate; hexo server` (from Powershell)

And I just see the plain arrows as if the plugin haven't be executed 😢 What did I do wrong?

I used this as a test article:
```
---
title: test
date: 2018-06-18 16:50:09
tags:
---
# Test11
## Test22
->blabla<-
### Test33
```

PS: For the emoji question: how can I use **twemoji** instead of the OS ones without modifying your plugin source files?

**Comment by CHENXCHEN** [comment]
Hi,  
This plugin works fine.
 `_config.yml` shoud as below:
```
markdown_it_plus:
    plugins:
        - plugin:
            name: markdown-it-center-text
            enable: true
```
