### ISSUE TITLE
如何更换公式的渲染？

### ISSUE THREAD

**Issue by inkss** [CHENXCHEN/hexo-renderer-markdown-it-plus#18]
你好，我先在配置里把 `markdown-it-katex` 关掉了：

```yml

```markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    plugins:
        - plugin:
            name: '@iktakahiro/markdown-it-katex'
            enable: false
```

然后安装了 `hexo-math` ，但是发现文章公式部分并没有渲染，请问如何解决呢？
