### ISSUE TITLE
公式渲染无法使用

### ISSUE THREAD

**Issue by xiang578** [CHENXCHEN/hexo-renderer-markdown-it-plus#20]
按照 README 文件中的方法安装插件之后，无法渲染公式。比如这个 https://xiang578.com/2018/10/01/math-test/ 页面，查看网页源代码，已经将 katex 的文件导入了。

_config.yml 的相关配置如下：
 ```
markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  plugins:
    - plugin:
        name: markdown-it-katex
        enable: true
    - plugin:
        name: markdown-it-mark
        enable: false
```
