### ISSUE TITLE
Extra new line on footnote 

### ISSUE THREAD

**Issue by Aqua-Dream** [CHENXCHEN/hexo-renderer-markdown-it-plus#23]
``` yml
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-all-minifier": "^0.5.3",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-markdown-it-plus": "^1.0.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.4.4"
  }
```

My source file:
``` md
---
title: test
date: 2019-03-21 00:31:06
tags:
---

Footnote test[^1].

[^1]: https://tieba.baidu.com/p/3551069391
```
Behavior:
![image](https://user-images.githubusercontent.com/17526818/54702094-2d01ef80-4b71-11e9-85aa-b2037681ca27.png)

Where the extra new line is marked by a red arrow.
