### ISSUE TITLE
how to use markdown-it-highlight-lines

### ISSUE THREAD

**Issue by xiaohun254700** [CHENXCHEN/hexo-renderer-markdown-it-plus#36]
我尝试在使用这个库的时候整合markdown-it-highlight-lines这个第三方插件包。
但是它似乎不生效。
```
markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  plugins:
    - plugin:
        name: markdown-it-highlight-lines
        enable: true
```
