### ISSUE TITLE
插件 "markdown-it-obsidian-callouts" 无法使用

### ISSUE THREAD

**Issue by rt265** [CHENXCHEN/hexo-renderer-markdown-it-plus#38]
作者你好，

感谢你的渲染器！我现在还有一个问题：我启用了 [markdown-it-obsidian-callouts](https://github.com/ebullient/markdown-it-obsidian-callouts)，但插件似乎没有工作。根据插件作者的样例，当使用 Callout 时，引用框应该被渲染成自定义的 Callout 样式。但当我使用其提供的样例进行测试时，却发现生成的是一般的 blockqoute 样式。

我做了以下步骤：
1. `sudo npm install markdown-it-obsidian-callouts --save`
2. 修改 `_config.yml`:
```yml
markdown_it_plus:
highlight: true
html: true
xhtmlOut: true
breaks: true
langPrefix:
linkify: true
typographer:
quotes: “”‘’
pre_class: highlight
plugins:
  - plugin:
    name: markdown-it-obsidian-callouts
    enable: true
```
3. 新建测试文件 `CalloutTest.md`:
```markdown
---
title: CalloutTest
tags: []
categories: []
date: 2025-01-28 12:08:45
description:
topic:
---
> [!note] title
> Hello World!
> > [!warning] a warning
> > This is a nested warning callout
```
4. 依次运行 `hexo clean`, `hexo generate`, `hexo server`

根据插件作者的说法，生成的 HTML 文件为应该：
```html
<div class="callout" data-callout="note">
  <div class="callout-title">
    <div class="callout-title-icon">
      <svg ... class="lucide lucide-pencil"> ... </svg>
    </div>
    <div class="callout-title-inner">title</div>
  </div>
  <div class="callout-content">
    <p>Hello World!</p>
    <div class="callout" data-callout="warning">
      <div class="callout-title">
        <div class="callout-title-icon">
          <svg ... class="lucide lucide-alert-triangle"> ... </svg>
        </div>
        <div class="callout-title-inner">a warning</div>
      </div>
      <div class="callout-content">
        <p>This is a nested warning callout</p>
      </div>
    </div>
  </div>
</div>
```
但实际上生成：
```html
<blockquote>
  <p>[!note] title<br>
  Hello World!</p>
  <blockquote>
    <p>[!warning] a warning<br>
    This is a nested warning callout</p>
  </blockquote>
</blockquote>
```

这里有出现什么问题吗？或者我需要向插件作者寻求帮助？
