### ISSUE TITLE
[TOC] anchor problem

### ISSUE THREAD

**Issue by zhangyu0806** [CHENXCHEN/hexo-renderer-markdown-it-plus#4]
Hexo 导航栏 TOC 锚点无效，且只生成一级目录
之前用[hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it) 渲染 Markdown 的话，会出现导航无法使用，且只出现一级标题的情况。
[TOC锚点初始化失败？ #974](https://github.com/iissnan/hexo-theme-NexT/issues/974)
解决方案如下 ↓
[Cannot render headings with ids? #40](https://github.com/hexojs/hexo-renderer-markdown-it/issues/40)
- - - - -
重新安装 hexo-renderer-markdown-it-plus ，似乎之前的 hexo-renderer-markdown-it 存在的问题继承下来了。
且用 `@[toc]` 生成 Table of Contents 后，导航栏的层级错乱，无法导航。
![](http://odandsezm.bkt.clouddn.com/Hexo/_image/2017-10-13-22-30-14.jpg)
这个是否可以用 [Cannot render headings with ids? #40](https://github.com/hexojs/hexo-renderer-markdown-it/issues/40) 此办法修复？

**Comment by CHENXCHEN** [comment]
关于TOC锚点，我使用的是`markdown-it-toc-and-anchor`，并且在我的测试下是有效的，您可以看我的这篇`blog`，点击右侧`Table of Contents`，其下的导航锚点是有效的，[样例文章](https://chchc.me/hexo-article/2016/07/30/CF-Educational-Codeforces-Round-15/)
并且在本地测试，通过`@[TOC]`生成的锚点效果上来看也是正常的。
ps: `hexo-renderer-markdown-it `插件没有集成完整的`TOC`的相关插件和语法所以有bug

**Comment by CHENXCHEN** [comment]
也许以下几种方法可以帮您解决这个问题：
1. `hexo clean`之后再测试`hexo g`
2. 删除`node_modules`并重新安装依赖包`npm install`
3. 升级`hexo`版本

**Comment by zhangyu0806** [comment]
感谢作者耐心解答。之前没注意到 Hexo 配置文件中少添加了 `render:`
![](http://odandsezm.bkt.clouddn.com/Hexo/_image/2017-10-14-14-42-37.jpg)

另，你的说明文档里没写这行，容易造成误解：）

**Comment by CHENXCHEN** [comment]
@zhangyu0806 markdown_it_plus下没有render这一行..,文档里有写配置信息

**Comment by zhangyu0806** [comment]
```
markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    pre_class: highlight
```
重新改了 Hexo 配置文件， 之前配置后没 hexo clean 。
