### ISSUE TITLE
奇怪的部分渲染问题

### ISSUE THREAD

**Issue by GalAster** [CHENXCHEN/hexo-renderer-markdown-it-plus#8]
### 部分行内公式渲染, 部分没渲染

![image](https://user-images.githubusercontent.com/17541209/36625645-80f79a9a-195e-11e8-8364-3157afd739e7.png)

#### 网页链接

https://galaster.github.io/archives/59dcbda5.html

---

#### package.json

```json
"dependencies": {
    "hexo": "^3.2.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-all-minifier": "^0.5.2",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.0.0",
    "hexo-inject": "^1.0.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-markdown-it-plus": "^1.0.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "hexo-symbols-count-time": "^0.3.2",
    "live2d-widget-model-koharu": "^1.0.5"
  }
```

#### _config.yml

默认设置

#### theme/next/_config.yml

```yaml
math:
  enable: true
  per_page: false # If you set it to false, it will load mathjax/katex srcipt EVERY PAGE.
  engine: katex
  katex:
    cdn: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css
```

不过我看 demo 用的也是 next 主题

#### 项目快照

https://github.com/GalAster/Galaster.github.io/tree/8fb4db43b356a5ef5b2255cae7d2d61290d85c8f
